import React, { useState } from 'react';
import { NATIONAL_DATA } from '../data/content';
import { Truck, Users, ExternalLink, ArrowRight, CheckCircle2 } from 'lucide-react';

interface CollectionSankeySectionProps {
  onOpenSources: (id?: string) => void;
}

export const CollectionSankeySection: React.FC<CollectionSankeySectionProps> = ({ onOpenSources }) => {
  const [selectedChannel, setSelectedChannel] = useState<'ulb' | 'informal'>('ulb');

  const { collection } = NATIONAL_DATA.postConsumer;

  return (
    <section
      id="collection"
      className="py-20 px-4 sm:px-6 lg:px-8 max-w-6xl mx-auto border-b border-[#D4D0C7]"
    >
      {/* Editorial Marker */}
      <div className="flex items-center gap-2 font-mono text-xs text-[#65785F] uppercase font-semibold mb-3">
        <span>ACT IV : THE LOGISTICS OF DEPARTURE</span>
        <span className="text-[#D4D0C7]">/</span>
        <span>SECTION 05</span>
      </div>

      {/* Heading */}
      <div className="max-w-3xl mb-12">
        <h2 className="font-serif text-3xl sm:text-5xl md:text-6xl text-[#191919] font-normal leading-tight mb-4">
          Your T-shirt leaves home.
        </h2>
        <p className="font-sans text-base sm:text-lg text-[#6F6C66] font-light leading-relaxed">
          In India, post-consumer textile waste does not pass through a single municipal recycling container.
          Instead, it splits into two vastly different collection systems:
        </p>
      </div>

      {/* Interactive Flow Visualizer */}
      <div className="p-6 sm:p-10 bg-[#FAF8F5] border border-[#D4D0C7] mb-8">
        {/* Channel Selection Toggle */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-[#D4D0C7]">
          <div>
            <span className="font-mono text-xs uppercase text-[#6F6C66] block">Collection Channel Breakdown</span>
            <span className="font-serif text-2xl text-[#191919]">Where 4.10M Tonnes Go First</span>
          </div>

          <div className="flex items-center gap-2 p-1 bg-[#E5E0D5] rounded border border-[#D4D0C7]">
            <button
              onClick={() => setSelectedChannel('ulb')}
              className={`px-3 py-1.5 text-xs font-mono font-medium rounded transition-all ${
                selectedChannel === 'ulb'
                  ? 'bg-[#191919] text-[#F2EFE8] shadow-xs'
                  : 'text-[#191919] hover:text-[#000]'
              }`}
            >
              Urban Local Bodies ({collection.ulbPercent}%)
            </button>
            <button
              onClick={() => setSelectedChannel('informal')}
              className={`px-3 py-1.5 text-xs font-mono font-medium rounded transition-all ${
                selectedChannel === 'informal'
                  ? 'bg-[#191919] text-[#F2EFE8] shadow-xs'
                  : 'text-[#191919] hover:text-[#000]'
              }`}
            >
              NGOs &amp; Informal ({collection.informalPercent}%)
            </button>
          </div>
        </div>

        {/* Sankey / Flow diagram */}
        <div className="relative py-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 sm:gap-6 relative">
            {/* Stage 1: Wardrobe */}
            <div className="p-4 bg-[#F2EFE8] border border-[#D4D0C7] flex flex-col justify-between">
              <span className="font-mono text-[10px] text-[#6F6C66] uppercase">STAGE 1: ORIGIN</span>
              <div className="my-3">
                <h4 className="font-serif text-xl text-[#191919]">Urban Closets</h4>
                <p className="font-sans text-xs text-[#6F6C66] mt-1">4,100 KTPA generated by households</p>
              </div>
              <div className="font-mono text-xs font-bold text-[#191919] pt-2 border-t border-[#D4D0C7]">
                100% of post-consumer
              </div>
            </div>

            {/* Stage 2: Channels (ULB vs Informal) */}
            <div
              className={`p-4 border transition-all cursor-pointer ${
                selectedChannel === 'ulb'
                  ? 'bg-[#FAF8F5] border-[#191919] ring-2 ring-[#191919]'
                  : 'bg-[#F2EFE8] border-[#D4D0C7] opacity-80'
              }`}
              onClick={() => setSelectedChannel('ulb')}
            >
              <div className="flex items-center justify-between font-mono text-[10px] text-[#6F6C66] uppercase">
                <span>STAGE 2A: FORMAL</span>
                <Truck className="w-3.5 h-3.5 text-[#191919]" />
              </div>
              <div className="my-3">
                <h4 className="font-serif text-xl text-[#191919]">Urban Local Bodies</h4>
                <p className="font-sans text-xs text-[#6F6C66] mt-1">Municipal garbage trucks &amp; dumpsites</p>
              </div>
              <div className="font-mono text-xs font-bold text-[#A64B32] pt-2 border-t border-[#D4D0C7] flex justify-between">
                <span>{collection.ulbPercent}%</span>
                <span>{collection.ulbKTPA} KTPA</span>
              </div>
            </div>

            {/* Stage 2B: Informal */}
            <div
              className={`p-4 border transition-all cursor-pointer ${
                selectedChannel === 'informal'
                  ? 'bg-[#FAF8F5] border-[#191919] ring-2 ring-[#191919]'
                  : 'bg-[#F2EFE8] border-[#D4D0C7] opacity-80'
              }`}
              onClick={() => setSelectedChannel('informal')}
            >
              <div className="flex items-center justify-between font-mono text-[10px] text-[#6F6C66] uppercase">
                <span>STAGE 2B: INFORMAL</span>
                <Users className="w-3.5 h-3.5 text-[#65785F]" />
              </div>
              <div className="my-3">
                <h4 className="font-serif text-xl text-[#191919]">Informal &amp; NGOs</h4>
                <p className="font-sans text-xs text-[#6F6C66] mt-1">Waghri traders, kabadiwalas &amp; charities</p>
              </div>
              <div className="font-mono text-xs font-bold text-[#65785F] pt-2 border-t border-[#D4D0C7] flex justify-between">
                <span>{collection.informalPercent}%</span>
                <span>{collection.informalKTPA} KTPA</span>
              </div>
            </div>

            {/* Stage 3: Aggregation & Outcome */}
            <div className="p-4 bg-[#F2EFE8] border border-[#D4D0C7] flex flex-col justify-between">
              <span className="font-mono text-[10px] text-[#6F6C66] uppercase">STAGE 3: FATE</span>
              <div className="my-3">
                <h4 className="font-serif text-xl text-[#191919]">Downstream Split</h4>
                <p className="font-sans text-xs text-[#6F6C66] mt-1">Sorting hubs, markets or landfills</p>
              </div>
              <div className="space-y-1 font-mono text-[11px] pt-2 border-t border-[#D4D0C7]">
                <div className="flex justify-between text-[#65785F]">
                  <span>55% Recovery:</span>
                  <span>2,255 KTPA</span>
                </div>
                <div className="flex justify-between text-[#A64B32]">
                  <span>45% Landfill:</span>
                  <span>1,845 KTPA</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Selected Channel Deep Dive Callout */}
        <div className="mt-8 p-5 bg-[#FAF8F5] border border-[#D4D0C7] rounded">
          {selectedChannel === 'ulb' ? (
            <div>
              <div className="flex items-center gap-2 text-xs font-mono font-bold text-[#A64B32] uppercase mb-1">
                <Truck className="w-4 h-4" />
                <span>Urban Local Bodies (66% · 2,725 KTPA)</span>
              </div>
              <h5 className="font-serif text-xl text-[#191919] mb-2">
                Mixed Municipal Waste is a Textile Death Sentence
              </h5>
              <p className="font-sans text-sm text-[#6F6C66] leading-relaxed">
                When a garment is tossed into regular domestic garbage, it mingles with wet kitchen waste, food oils, and
                decomposing organics. By the time it arrives at municipal dump transfer stations, natural cotton fibres
                are soiled and bio-contaminated. Cleaning costs often surpass the recycled fiber value, which is why a
                staggering share of ULB-collected clothing goes directly to landfills like Ghazipur or Deonar.
              </p>
            </div>
          ) : (
            <div>
              <div className="flex items-center gap-2 text-xs font-mono font-bold text-[#65785F] uppercase mb-1">
                <Users className="w-4 h-4" />
                <span>NGOs, Door-to-Door Collectors &amp; Chindi Traders (34% · 1,375 KTPA)</span>
              </div>
              <h5 className="font-serif text-xl text-[#191919] mb-2">
                The Invisible Labor Force of Circularity
              </h5>
              <p className="font-sans text-sm text-[#6F6C66] leading-relaxed">
                Communities like the Waghri community exchange stainless steel utensils for old clothing door-to-door.
                These garments remain dry and clean. They are sorted into Sunday flea markets (chor bazaars) for low-income
                families, while unwearable remnants are sold as industrial cotton wipes (chindi) or sent to Panipat for
                shredding. This informal network recovers textiles with nearly zero municipal investment.
              </p>
            </div>
          )}
        </div>

        {/* Source citation */}
        <div className="mt-6 pt-4 border-t border-[#D4D0C7] flex justify-between items-center text-xs font-mono text-[#6F6C66]">
          <span>Data: Ministry of Textiles (2026), Table 4.2</span>
          <button
            onClick={() => onOpenSources('mot-2026')}
            className="text-[#65785F] hover:underline flex items-center gap-1"
          >
            <span>Verify Collection Data</span>
            <ExternalLink className="w-3 h-3" />
          </button>
        </div>
      </div>
    </section>
  );
};
